Status Table Page
BrightspaceUI/documentation pull request #144
Opened 2021-06-02 15:18 UTC by margaree

This PR adds the following:
- Status table page with tables for Official, Labs, and Request components (based on labels on issues - modifies the issue templates as needed)
- Each component has a page. If `devMarkdown` is included (meaning the component has complete documentation) then that is used as the page, else generate a page from the GitHub issue body

2021-06-02 16:41 UTC, margaree commented on pages/components/status.md
> +This page lists all our components, including [Labs]() components and even [requested]() components that haven't been built yet. We include the overall status of the component, but you can get the fu
Links currently don't go anywhere yet.

2021-06-02 16:41 UTC, margaree commented on tools/generate-pages.mjs
> +function _getDevStatus(labels, state, issueState) {
For getting the dev status I added "Deprecated" and "Backlog" labels since something can have Complete development but be deprecated or something can have a not started dev state but be on the backlog or not planned.

I added the fallback assumption of complete or not started in case there are typos. We can also add labels for "Development In Progress" etc but my worry would be that if we bring design statuses back in, there could be an excessive amount of labels.

2021-06-02 16:41 UTC, margaree commented on tools/generate-pages.mjs
> +import { DEV_STATES, ISSUE_LABELS } from './states.mjs';
This file was getting overly complicated, especially with the generating of pages from issues that don't have documentation, so I tried to do some rearranging to make it a bit more straightforward.

2021-06-02 16:41 UTC, margaree commented on tools/states.mjs
> +export const CC_STATES = {
I split these all out in case they have changes in terminology - `CC_STATES` are the states that show up in the status table (and could end up as a combination of dev and design states, though currently they are just determined by dev state), `DEV_STATES` are determined through the state in the issue comment and the labels on it.

2021-06-03 15:06 UTC, GeorgePlukov requested changes

2021-06-03 15:44 UTC, dlockhart commented on .eleventy.js
> +					<<div class="d2l-component-catalog-tag-inner">${tag}</div>>
Looks like some extra `<` and `>` snuck in here? If they were intentional to show the tag name, probably better to use `&lt;` and `&gt;`.

2021-06-03 15:44 UTC, dlockhart commented on pages/assets/status-table.js
> +			type: { type: String },
I'm fine not documenting components like this that are purely internal to the catalogue.

2021-06-03 15:44 UTC, dlockhart commented on pages/assets/status-table.js
> +		this._components.sort((a, b) => {
Would it make sense for the generated issue data to already be sorted alphabetically? Would save runtime client-side sorting over and over again.

2021-06-03 15:44 UTC, dlockhart commented on pages/assets/status-table.js
> +				: html `<d2l-link class="d2l-component-catalog-status-table-name" href="${linkHref}">${component.name}<img src="/img/${this.type}-icon.svg" alt="${this.type} icon"></d2l-link>`;
`alt` on this image can be likely be null... the fact that it's labs/etc. should already have been captured by the heading above this table and likely doesn't need to be repeated with each one?

2021-06-03 15:44 UTC, dlockhart commented on pages/assets/status-table.js
> +				<table class="d2l-table">
This ends up being super clean, love it!

2021-06-03 15:44 UTC, dlockhart commented on pages/components/status.md
> +Official components adhere to our architectural guidelines, are localized and highly performant. They have a full suite of automated tests (include accessibility and perceptual diff), a demo page, an
I know you just lifted this from the Guide, but we've coalesced around "visual diff" so I think we should use that terminology here. I've updated the Guide to do the same.

```suggestion
Official components adhere to our architectural guidelines, are localized and highly performant. They have a full suite of automated tests (including accessibility and visual diff), a demo page, and appropriate documentation.
```

2021-06-03 15:44 UTC, dlockhart commented on pages/components/status.md
> +Components that fall into the "labs" tier have some buy-in from design, at least in an experimental sense. They may not have a full pattern documented on design.d2l yet, but some design thought has g
Margaree's mostly borrowing from [this page in the Guide](https://github.com/BrightspaceUI/guide/wiki/Component-Tiers). I agree though that "buy-in" is a little weird. "Support"?

Agree that we likely don't want to mention design.d2l here since the Catalogue will in all likelihood be replacing it:

```suggestion
Components that fall into the "labs" tier have some support from design, at least in an experimental sense. Some design thought has gone into the component and where and how it should be used. The component has the potential to be used in multiple places.
```

Another option would be to exclude this stuff entirely from this particular page and just show the tables, and then we move all the info about tiers -- why we have them, what they are, etc. -- into the secondary doc that you linked to above on Component Tiers.

2021-06-03 15:44 UTC, dlockhart commented on pages/components/status.md
> +Labs components may not fully adhere to archutectural guidelines, and may be missing some tests or documentation.
```suggestion
Labs components may not fully adhere to architectural guidelines, and may be missing some tests or documentation.
```

2021-06-04 13:20 UTC, margaree commented on pages/components/status.md
> +Components that fall into the "labs" tier have some buy-in from design, at least in an experimental sense. They may not have a full pattern documented on design.d2l yet, but some design thought has g
So the wording in the status page is pretty much just directly copied from Jeff's design for the page. I like the suggestions though. I'll make them and run them by him to confirm.

2021-06-04 13:21 UTC, margaree commented on .eleventy.js
> +					<<div class="d2l-component-catalog-tag-inner">${tag}</div>>
They are intentional to show the tag. `&lt;` and `&gt;` do seem better - will change.

2021-06-04 13:22 UTC, margaree commented on pages/components/status.md
> +Labs components may not fully adhere to archutectural guidelines, and may be missing some tests or documentation.
🤦‍♀️

2021-06-07 18:00 UTC, GeorgePlukov approved these changes

2021-06-07 19:34 UTC, merged