Writing page > Major additions/changes
BrightspaceUI/documentation pull request #1508
Opened 2023-11-21 02:53 UTC by geurts

Major additions and changes to Writing page documentation. Some style changes in the scope of the Writing page. Also some style tweaks to the global styles in `page-content.css` that should not affect component pages.

2023-11-22 16:41 UTC, nicolebezaire requested changes
Yey! SO rewarding to see my updates to the Writing style guide go to implementation. See my revision requests over in our slack thread :)

2023-12-08 21:45 UTC, geurts commented on pages/_includes/css/page-content.css
> +.d2l-daylight-dos, .d2l-daylight-donts {
Doesn't seem to be necessary, but happy to re-add it if you think it's better to be more specific?

2023-12-08 21:46 UTC, geurts commented on pages/style-elements/writing.md
> +    src: url("../_includes/BodoniModa-VariableFont_opsz,wght.ttf");
It's how the file was named by google fonts. I thought about simplifying to "BodoniModa.ttf" but thought it was probably better to leave it. Should I simplify it then?

2023-12-08 22:18 UTC, geurts commented on pages/style-elements/writing.md
> +    src: url("../_includes/BodoniModa-VariableFont_opsz,wght.ttf");
Was able to remove the web font anyway, yey :)

2023-12-08 22:18 UTC, geurts commented on pages/style-elements/writing.md
> +    <div style="text-align:start;font-size:.9em;color:var(--d2l-color-galena);">Viljami Salminen</div>
Done!

2023-12-08 22:19 UTC, geurts commented on pages/style-elements/writing.md
> +<p style="margin-top:-12px !important">For further detail and definition, check out <a href="https://desire2learn.atlassian.net/wiki/spaces/PD/pages/1487310133/Activity+Re-use+and+Sharing+Language">A
I actually removed that, yeah. Strange that originally it addressed a gap that was too large, not sure what changed but happy to have it removed 🤷

2023-12-11 13:59 UTC, margaree commented on pages/_includes/css/page-content.css
> +.d2l-daylight-dos, .d2l-daylight-donts {
If it's not necessary then I'd say leave it out

2023-12-15 16:13 UTC, margaree approved these changes

2023-12-15 16:37 UTC, nicolebezaire approved these changes
👍

2023-12-15 16:44 UTC, merged