Add default value option to demos, other tweaks
BrightspaceUI/documentation pull request #181
Opened 2021-06-29 20:45 UTC by margaree

This allows for demos to set default attribute values. Also some other tweaks I found when adding Button page.

2021-06-29 20:52 UTC, margaree commented on .eleventy.js
> +					else if (token.tag === 'h3') headingClass += ' d2l-heading-4';
I switched this to be styled like an h4 since that's what's happening in the `demo-tables` so this keeps that consistent.

2021-06-29 20:52 UTC, margaree commented on pages/assets/demo-snippet.js
> -						case 'String':
Switched this to be an object and use the same casing.

2021-06-29 20:52 UTC, margaree commented on pages/assets/demo-snippet.js
> +				const value = defaults[key];
I'm making an assumption that values will be sent as `"string"` or `14` (number) or `true / false` without quotes around the numbers or booleans and so we can pull type from that.

2021-06-29 20:52 UTC, margaree commented on pages/assets/demo-snippet.js
> -	_parseConfigurationValue(tag) {
This got moved to the utils file for testing.

2021-06-29 20:52 UTC, margaree commented on pages/assets/demo-tables.js
> +		this._componentInfo.attributes.sort((a, b) => {
I added a sort so that `required` attributes are first, following by alphabetical order, which is currently not guaranteed (I think order goes file properties, then mixin properties)

2021-06-29 20:52 UTC, margaree commented on pages/assets/demo-tables.js
> +					if (defaultForName) initialValue = info.type !== 'string' ? `"${defaultForName}"` : defaultForName;
The current logic fails if the value is `true` and it isn't wrapped with `"` so I just wrapped everything with quotes.

2021-06-29 20:52 UTC, margaree commented on pages/assets/demo-tables.js
> +		const slotRows = this._componentInfo.slots ? this._componentInfo.slots.map((slotInfo) => {
There was a console error so I added this check.

2021-06-29 20:52 UTC, margaree commented on pages/assets/utils.mjs
> +export function parseConfigurationValue(tag, demoSnippet, requireSplitOnNewlines) {
With `defaults`, we can't split on spaces and use inline since values can contain spaces (e.g., `"text": "My Button"`) so I made it necessary for if defaults is being used, this comment block must be split on newlines.

2021-06-30 17:59 UTC, GeorgePlukov requested changes
Pushed up a commit to add an example to the demo.md page I've been using. I think there is something going on with the `Interactive demo - size` example, it seems to render the property table fine in master and with the defaults option on this branch, but with single line comments its failing.

2021-06-30 17:59 UTC, GeorgePlukov commented on docs/adding-component.md
> +size:<'small'|'medium'|'large'|'xlarge'
Missing the closing `>` on this line and the opening one on the defaults line

2021-06-30 18:46 UTC, GeorgePlukov approved these changes

2021-06-30 18:55 UTC, merged