Code parsing: move comment to before code block
BrightspaceUI/documentation pull request #183
Opened 2021-07-01 12:59 UTC by margaree

This allows for the code information comment to come before the code block.

2021-07-05 17:40 UTC, GeorgePlukov approved these changes

2021-07-05 20:40 UTC, GeorgePlukov requested changes

2021-07-05 20:40 UTC, GeorgePlukov commented on .eleventy.js
> +			const size = parseConfigurationValue('size', content);
I was updating my branch with this and I _think_ the size value needs to be parsed outside of the if block and passed to any of the demo types (code demo/demo)

2021-07-06 13:11 UTC, margaree commented on .eleventy.js
> +			const size = parseConfigurationValue('size', content);
Ah okay - previously I don't think we were supporting that based on the original if statement since it looked for the entire `<!-- docs: demo -->` etc but I can switch that since that would make sense to support.

2021-07-06 13:12 UTC, margaree commented on .eleventy.js
> +			const size = parseConfigurationValue('size', content);
Any objection if I change the comments to all start with `<!-- docs: demo` and then there'd be `<!-- docs: demo live`, `<!-- docs: demo code` and just `<!-- docs: demo` since that would make general parsing easier?

2021-07-06 14:00 UTC, GeorgePlukov commented on .eleventy.js
> +			const size = parseConfigurationValue('size', content);
Oh wow, I swear that I removed the closing fences from those at some point! And yeah that naming seems alright to me, I think those are referenced in the docs a couple places as well

2021-07-06 18:36 UTC, margaree commented
@GeorgePlukov This is ready for a re-review when you have a chance (no rush). If the `$attributes` related changes seem to be possible then I'll put up a separate PR for that.

2021-07-07 15:23 UTC, GeorgePlukov approved these changes

2021-07-07 15:35 UTC, merged